//Auth action types
export const AUTH = 'AUTH';
export const INITIATE_LOGIN = 'INITIATE_LOGIN';
export const INITIATE_LOGOUT = 'INITIATE_LOGOUT';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_FAIL = 'LOGOUT_FAIL';
export const ATTEMPT_REFRESH = 'ATTEMPT_REFRESH';

//Widget action types
export const START_ADD_WIDGET = 'START_ADD_WIDGET';
export const ADD_WIDGET_SUCCESS = 'ADD_WIDGET_SUCCESS';
export const ADD_WIDGET_FAIL = 'ADD_WIDGET_FAIL';
export const START_REMOVE_WIDGET = 'START_REMOVE_WIDGET';
export const REMOVE_WIDGET_SUCCESS = 'REMOVE_WIDGET_SUCCESS';
export const REMOVE_WIDGET_FAIL = 'REMOVE_WIDGET_FAIL';
export const INIT_WIDGETS = 'INIT_WIDGETS';
export const SET_WIDGETS = 'SET_WIDGETS';
